version: '2'
services:

  web:
    image: node:6
    working_dir: /src
    volumes:
      - .:/src
    command:
      - ./start.sh
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: dwikia
    links:
      - mongo:mongo
    depends_on:
      - mongo
    expose:
      - 4000
      - 5859
    ports:
      - 5859:5859
      - 4000:4000

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27017

