version: '3'
services:

  frontend:
    image: nginx:alpine
    working_dir: /usr/share/nginx/html
    volumes:
      - ./app:/usr/share/nginx/html:ro
    ports:
      - 80:80
    # depends_on:
      # - mongo
      # - backend

  backend:
    image: node:14
    working_dir: /src
    volumes:
      - .:/src
    command:
      - app.js
    env_file:
      - docker-compose-env
    ports:
      - 5859:5859
      - 4000:4000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - cache-data:/data/db

volumes:
  cache-data:
