version: '3'
services:

  web:
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    # image: rickydunlop/nodejs-ffmpeg
    image: node:14
    working_dir: /src
    volumes:
      - .:/src
    command:
      - ./start.sh
    env_file:
      - docker-compose-env
    ports:
      - 5859:5859
      - 4000:4000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - cache-data:/data/db

volumes:
  cache-data:
